version: '3.8'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projeto_node
    volumes:
      - projeto_node_pg_data:/bitnami/postgresql

  redis:
    image: bitnami/redis:latest
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - projeto_node_redis_data:/bitnami/redis/data

volumes:
  projeto_node_pg_data:
  projeto_node_redis_data:
